uploads = []
outputs = []

[[generated]]
id = "qEvymFlmCuyz-QmntZk0l"
uri = "file://artifacts/rattrap-ppt/public/images/cover-road.png"
type = "image"
title = "generated_image"

[[generated]]
id = "86J3ZgPv5xjA3eg5lN6RK"
uri = "file://artifacts/rattrap-ppt/public/images/rattrap.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qxDQ3ELl_hwhz5J5qYH6J"
uri = "file://artifacts/rattrap-ppt/public/images/forest-path.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BREZHkSsj-Qf2CnRlGq-Q"
uri = "file://artifacts/rattrap-ppt/public/images/cottage.png"
type = "image"
title = "generated_image"

[[generated]]
id = "aiosnUhl1Blmfs_Z1hro3"
uri = "file://artifacts/rattrap-ppt/public/images/conclusion.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tW3pzF2lo4loyUPLBmdhP"
uri = "file://artifacts/rattrap-ppt/public/images/thankyou.png"
type = "image"
title = "generated_image"
